<a href="https://colab.research.google.com/github/Onmang/Multimedia_engineering/blob/master/T20ME022_EX05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as np

def main():
  A = np.loadtxt('/content/drive/MyDrive/enshu.txt')
  ave = np.mean(A)
  std = np.std(A)
  A_inv = np.linalg.inv(A)
  
  print(f'A＝\n{A}\n平均値＝{ave:.4f}\n標準偏差＝{std:.3f}\n逆行列＝\n{A_inv}')

if __name__ =="__main__":
  main()

A＝
[[ 1.  3. -2.  5.]
 [ 0.  2.  5. -1.]
 [ 1.  2. -3. -4.]
 [-1.  5.  2.  0.]]
平均値＝0.9375
標準偏差＝2.680
逆行列＝
[[ 0.2917847   0.45042493  0.25212465 -0.45609065]
 [ 0.05949008  0.01416431  0.07082153  0.13031161]
 [-0.00283286  0.1898017  -0.0509915  -0.05382436]
 [ 0.10481586 -0.02266289 -0.11331445 -0.00849858]]
